### ISSUE TITLE
v0.0.10 breaks builder ButtonBox

### ISSUE THREAD

**Issue by wieluk** [psychopy/psychopy-cedrus#22]
When trying to add a ButtonBox component in the builder this error appears:

```
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\builder\builder.py", line 2868, in onClick
    comp = self.component(
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\experiment\components\buttonBox\__init__.py", line 140, in __init__
    self.loadBackends()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\experiment\plugins.py", line 47, in loadBackends
    backend.addRequirements(self)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\experiment\plugins.py", line 109, in addRequirements
    raise NotImplementedError()
NotImplementedError
```

I am on psychopy 2024.2.4 and windows 11.

**Comment by TEParsons** [comment]
Fixed in https://github.com/psychopy/psychopy-cedrus/commit/967ec017e81ca4430d2fc2db087576fb88ad8097
